### ISSUE TITLE
 adaptive kernel

### ISSUE THREAD

**Issue by gs-max** [HotChieh/BDRNet#1]
您好，首先感谢您出色的工作。其次我在看代码的时候发现您提到 adaptive kernel方面有一些bug，请问现在修复了吗？还有就是您提供的OneDrive中的shanghaitech数据集是经过您的dataset里面的代码处理之后的数据集吗？

**Comment by HotChieh** [comment]
你好，感谢关注。1）目前我再次于github下载上传的代码并测试，按照主目录下的readme环境可一次运行，无任何bug，所以不知道你提到的bug指的是什么，可以贴出来帮忙分析一下。2）本论文主要聚焦遥感图像（鸟瞰视角）中的目标计数任务，SHHA数据集本论文并未关注，datasets文件夹下SHHA中的readme不是本文原创，建议查看监控视角领域的人群相关工作。
